#!/usr/bin/env python3
"""
generate_digest.py
Reads multi-repo activity JSON, calls Gemini, outputs markdown digest.
Usage: python generate_digest.py activity.json > digest.md
"""
import os
import json
import sys
import urllib.request
from datetime import datetime, timezone

def load_activity(path: str) -> dict:
    with open(path) as f:
        return json.load(f)

def repo_summary(r: dict) -> str:
    if "error" in r:
        return f"### {r['repo']}\n⚠️ Could not fetch: {r['error']}\n"
    commits   = r.get("commits", [])
    prs       = r.get("pull_requests", [])
    issues    = r.get("issues", [])
    ci_runs   = r.get("ci_runs", [])
    files     = r.get("changed_files", [])
    failed_ci = [x for x in ci_runs if x.get("conclusion") == "failure"]
    merged_pr = [p for p in prs if p.get("merged")]
    open_pr   = [p for p in prs if p["state"] == "open" and not p.get("merged")]
    bugs      = [i for i in issues if any(l in ["bug","critical","blocker"] for l in i.get("labels", []))]
    return f"""
### {r['repo']}
Commits: {len(commits)} | PRs open: {len(open_pr)} merged: {len(merged_pr)} | Issues: {len(issues)} (bugs: {len(bugs)}) | CI failures: {len(failed_ci)} | Files changed: {len(files)}
Recent commits: {json.dumps([c['message'] for c in commits[:5]])}
CI: {json.dumps([{"name": x["name"], "conclusion": x["conclusion"]} for x in ci_runs])}
Changed files: {json.dumps([f['filename'] for f in files[:10]])}
"""

def build_prompt(activity: dict) -> str:
    owner     = activity["owner"]
    window    = activity["window_hours"]
    generated = activity["generated_at"]
    repos     = activity.get("repos", [])
    total_commits = sum(len(r.get("commits", [])) for r in repos)
    total_prs     = sum(len(r.get("pull_requests", [])) for r in repos)
    total_issues  = sum(len(r.get("issues", [])) for r in repos)
    active_repos  = [r["repo"].split("/")[-1] for r in repos if r.get("commits")]
    sections = "\n".join(repo_summary(r) for r in repos)
    return f"""You are a senior engineering lead reviewing GitHub activity across a portfolio of projects.
All repos belong to developer: {owner}
Period: last {window} hours (as of {generated})
Portfolio totals: {total_commits} commits, {total_prs} PRs, {total_issues} issues across {len(repos)} repos.
Active repos (had commits): {active_repos}

Per-repo breakdown:
{sections}

Write a concise daily digest in this exact Markdown structure:

# Daily Digest — {owner}/Work-Flow-
*{datetime.now(timezone.utc).strftime("%A, %B %-d %Y")}*

## Overall pulse
2-3 sentences: what was the main theme of work today across all projects?

## Project activity
For EACH repo, one bullet line:
- **repo-name** — what happened (or "quiet day" if nothing)

## Spotlight: wins & concerns
Flag any: CI failures, stale PRs, open bugs, or repos with zero activity for 3+ days.
Also flag any repos showing strong momentum worth noting.

## Action items
4-6 specific things to do TODAY across the portfolio. Format: `[repo-name]` what to do.

---
*Generated by project-pop · Monitoring {len(repos)} repos*

Rules:
- ✅ good, ⚠️ needs attention, ❌ failure/blocker
- Under 600 words total
- If a section has nothing to report, write "Nothing to report" — don't skip it
- Be direct, not verbose
"""

def main():
    if len(sys.argv) < 2:
        print("Usage: generate_digest.py <activity.json>", file=sys.stderr)
        sys.exit(1)

    activity = load_activity(sys.argv[1])
    prompt   = build_prompt(activity)
    api_key  = os.environ["GEMINI_API_KEY"]

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"

    payload = json.dumps({
        "contents": [{"parts": [{"text": prompt}]}]
    }).encode("utf-8")

    req = urllib.request.Request(
        url,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    with urllib.request.urlopen(req) as resp:
        data = json.loads(resp.read().decode("utf-8"))

    print(data["candidates"][0]["content"]["parts"][0]["text"])

if __name__ == "__main__":
    main()
