#!/usr/bin/env python3
"""
generate_digest.py
Reads activity JSON, calls Claude AI, writes a clean markdown digest to stdout.
Usage: python generate_digest.py activity.json > digest.md
"""

import os
import json
import sys
import anthropic
from datetime import datetime, timezone

def load_activity(path: str) -> dict:
    with open(path) as f:
        return json.load(f)

def build_prompt(activity: dict) -> str:
    repo = activity["repo"]
    window = activity["window_hours"]
    generated = activity["generated_at"]

    commits = activity.get("commits", [])
    prs = activity.get("pull_requests", [])
    issues = activity.get("issues", [])
    ci_runs = activity.get("ci_runs", [])
    changed_files = activity.get("changed_files", [])

    failed_ci = [r for r in ci_runs if r.get("conclusion") == "failure"]
    merged_prs = [p for p in prs if p.get("merged")]
    open_prs = [p for p in prs if p["state"] == "open" and not p.get("merged")]
    bug_issues = [i for i in issues if any(l in ["bug", "critical", "blocker"] for l in i.get("labels", []))]

    data_summary = f"""
Repository: {repo}
Period: last {window} hours (as of {generated})

COMMITS ({len(commits)} total):
{json.dumps(commits[:10], indent=2)}

PULL REQUESTS ({len(prs)} updated):
- Merged: {len(merged_prs)}
- Open: {len(open_prs)}
{json.dumps(prs[:10], indent=2)}

ISSUES ({len(issues)} updated):
- Bug/critical: {len(bug_issues)}
{json.dumps(issues[:10], indent=2)}

CI RUNS ({len(ci_runs)} recent):
- Failed: {len(failed_ci)}
{json.dumps(ci_runs, indent=2)}

CHANGED FILES ({len(changed_files)} files):
{json.dumps(changed_files[:20], indent=2)}
"""

    return f"""You are a senior engineering lead reviewing your team's GitHub repository activity.

Analyze the following data from the last 24 hours and write a concise daily digest in Markdown.

Structure it exactly like this:

# Daily Digest — {repo}
*{datetime.now(timezone.utc).strftime("%A, %B %-d %Y")}*

## Summary
2-3 sentence overview of the day's activity — what was the main theme of work?

## Commits & code changes
Bullet summary of notable commits and file changes. Group by theme if possible.

## Pull requests
List open, merged, and any stale or draft PRs that need attention.

## Issues
Any new, updated, or critical issues. Flag bugs and blockers clearly.

## CI / build status
Status of CI pipelines. Call out failures with urgency if any.

## Action items
3-5 concrete things the team should do today based on this data. Be specific.

---
*Generated by GitHub Project Monitor · project-pop*

Rules:
- Be direct and useful, not verbose
- Use checkmark for good, warning for needs attention, X for failures/blockers
- If nothing happened in a section, say "Nothing to report" — don't skip the section
- Keep the whole digest under 500 words

Here is the data:
{data_summary}
"""

def main():
    if len(sys.argv) < 2:
        print("Usage: generate_digest.py <activity.json>", file=sys.stderr)
        sys.exit(1)

    activity = load_activity(sys.argv[1])
    prompt = build_prompt(activity)

    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )

    digest = message.content[0].text
    print(digest)

if __name__ == "__main__":
    main()
